[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Variáveis de ambiente para produção
[context.production.environment]
  NODE_ENV = "production"
  # Configure sua variável de ambiente VITE_MERCADO_LIVRE_CLIENT_ID no painel do Netlify

# Variáveis de ambiente para deploy preview
[context.deploy-preview.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecionamento específico para callback OAuth
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 