[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Variáveis de ambiente para produção
[context.production.environment]
  NODE_ENV = "production"
  # Configure suas variáveis de ambiente no painel do Netlify:
  # VITE_MERCADO_LIVRE_CLIENT_ID
  # VITE_MERCADO_LIVRE_CLIENT_SECRET

# Variáveis de ambiente para deploy preview
[context.deploy-preview.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 